#!/bin/bash

# Mark Glasgow :: 2336003G

# Task 7 ::
# Write a script (Task7.sh) which generates a directory with 10 files filled with 50 random numbers. 
# The script should test to see if the directory already exists before making it and exit with an error if it does. 
# The name of the directory should be the current time in timestamp format (this can be generated by capturing the output of the linux command date +%s). 
# The name of each file should be randomN.dat where N is a number between 1 to 10.



timestamp=$(date +%s)

# Check if directory exists - why though? this will be different for each run
if [ ! -d "$timestamp" ] # If timestamp isn't already a directory 
    
    then
	mkdir -p -- "$timestamp"
	echo Folder "$timestamp" created
    # exit in case cd fails
	cd "$timestamp" || exit
    
    # for loop to count 10 times
	for ((i = 1; i <= 10; i++))

        do 
            echo "Creating file randomN$i.txt"
            touch randomN$i.txt
            # Generate 50 random numbers
            for ((j = 1; j <= 50; j++))
                do 
                    echo $RANDOM ; 
                done > randomN$i.txt
        done
    # Return to the parent directory
	cd ..
    
    else
	echo "Error : Folder $timestamp already exists"

fi